#!/usr/bin/env bash
# Provision an ISOLATED Contract Management System instance for one ERP tenant.
#
# Why this exists: the vendored CMS (contracts/) is single-tenant — it has no
# tenant_id column, so one CMS instance = one organisation's data. The ERP is
# multi-tenant. Sharing a single CMS across ERP tenants would leak every
# tenant's contracts to the others. Adding row-level tenancy would mean forking
# the CMS schema, which breaks the git-subtree upgrade path (see CONTRACTS.md).
#
# So each tenant gets its own SILO: a separate database (cms_<slug>) inside the
# shared Postgres, its own backend + web containers, its own subdomain, and its
# own JWT signing secret. Nothing is shared between tenants except the Postgres
# server process and the Caddy TLS front door.
#
#   bash scripts/contracts-add-tenant.sh <slug> <subdomain>
#   e.g. bash scripts/contracts-add-tenant.sh acme contracts.acme.example.com
#
# Re-running is safe: an existing tenant's JWT secret is never overwritten.
set -euo pipefail

SLUG="${1:?usage: contracts-add-tenant.sh <slug> <subdomain>}"
DOMAIN="${2:?usage: contracts-add-tenant.sh <slug> <subdomain>}"

# slug must be a safe identifier (used in DB name, service names, volume names).
echo "$SLUG" | grep -qE '^[a-z][a-z0-9-]{0,30}$' || {
  echo "!! slug must match ^[a-z][a-z0-9-]{0,30}\$ (lowercase letter first, then letters/digits/dashes)" >&2
  exit 1
}

ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
DIR="$ROOT/deploy/contracts/$SLUG"
DB="cms_${SLUG//-/_}"   # Postgres identifiers can't contain dashes
mkdir -p "$DIR"

# --- per-tenant JWT secret (generated once, never overwritten) ----------------
# The CMS reads JWT_SECRET directly, so name it that: env_file values are
# injected into the container but are NOT available for ${...} interpolation
# in the compose file, so we can't remap the name there.
ENVFILE="$DIR/backend.env"
if [ ! -f "$ENVFILE" ]; then
  printf 'JWT_SECRET=%s\n' "$(openssl rand -hex 32)" > "$ENVFILE"
  chmod 600 "$ENVFILE"
  echo ">> wrote a new per-tenant JWT secret to $ENVFILE"
else
  echo ">> keeping the existing JWT secret in $ENVFILE"
fi

# --- Caddy site block: own subdomain, own auto-provisioned HTTPS cert ---------
cat > "$DIR/$SLUG.caddy" <<EOF
# Isolated contracts silo for tenant "$SLUG". Auto-generated — do not edit.
$DOMAIN {
	encode gzip
	handle /api/* {
		reverse_proxy contracts-backend-$SLUG:8000
	}
	handle {
		reverse_proxy contracts-web-$SLUG:80
	}
}
EOF

# --- compose overlay (all paths are relative to the repo root, which is the
#     compose project directory because docker-compose.prod.yml is the first -f)
cat > "$DIR/compose.yml" <<EOF
# Isolated CMS silo for tenant "$SLUG" ($DOMAIN).
# Generated by scripts/contracts-add-tenant.sh — regenerable, deployment-local.
x-logging: &log
  driver: json-file
  options: { max-size: '10m', max-file: '3' }

services:
  # Create this tenant's database in the shared Postgres if it's missing.
  contracts-init-$SLUG:
    image: postgres:16-alpine
    restart: 'no'
    logging: *log
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGPASSWORD: \${DATABASE_PASSWORD}
    entrypoint: ['sh', '-c']
    command:
      - >
        psql -h postgres -U \${DATABASE_USER:-erp_user} -d postgres -tc
        "SELECT 1 FROM pg_database WHERE datname='$DB'"
        | grep -q 1 ||
        psql -h postgres -U \${DATABASE_USER:-erp_user} -d postgres -c
        "CREATE DATABASE $DB"

  contracts-backend-$SLUG:
    build:
      context: ./contracts/backend
    restart: unless-stopped
    logging: *log
    depends_on:
      postgres:
        condition: service_healthy
      contracts-init-$SLUG:
        condition: service_completed_successfully
    env_file:
      - deploy/contracts/$SLUG/backend.env   # JWT_SECRET (unique per tenant)
    environment:
      DATABASE_URL: postgresql+psycopg2://\${DATABASE_USER:-erp_user}:\${DATABASE_PASSWORD}@postgres:5432/$DB
      ANTHROPIC_API_KEY: \${ANTHROPIC_API_KEY:-}
      APP_BASE_URL: https://$DOMAIN
      WATCH_ENABLED: 'false'
      EMAIL_DRY_RUN: \${CONTRACTS_EMAIL_DRY_RUN:-true}
      SMTP_HOST: \${SMTP_HOST:-}
      SMTP_PORT: \${SMTP_PORT:-587}
      SMTP_USER: \${SMTP_USER:-}
      SMTP_PASSWORD: \${SMTP_PASS:-}
      SMTP_FROM: \${SMTP_FROM:-}
      TIMEZONE: \${CONTRACTS_TIMEZONE:-Asia/Kolkata}
    volumes:
      - contracts_data_$SLUG:/app/data
      - contracts_uploads_$SLUG:/app/attachments
      - contracts_watched_$SLUG:/watched
    healthcheck:
      test:
        [
          'CMD',
          'python',
          '-c',
          "import urllib.request,sys; sys.exit(0 if urllib.request.urlopen('http://127.0.0.1:8000/api/health').status==200 else 1)",
        ]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 40s

  contracts-web-$SLUG:
    build:
      context: ./contracts/frontend
    restart: unless-stopped
    logging: *log
    depends_on:
      - contracts-backend-$SLUG

  # Give Caddy this tenant's site block. No depends_on: a broken tenant must
  # never block Caddy (and thus the ERP or other tenants).
  caddy:
    volumes:
      - ./deploy/contracts/$SLUG/$SLUG.caddy:/etc/caddy/conf.d/contracts-$SLUG.caddy:ro

volumes:
  contracts_data_$SLUG:
  contracts_uploads_$SLUG:
  contracts_watched_$SLUG:
EOF

echo ">> generated:"
echo "     $DIR/compose.yml"
echo "     $DIR/$SLUG.caddy"
echo "     $DIR/backend.env  (secret; gitignored, chmod 600)"
echo
echo ">> 1. Point a DNS A record for $DOMAIN at this server."
echo ">> 2. Bring it up (add one -f per tenant you run alongside the ERP):"
echo "     docker compose -f docker-compose.prod.yml \\"
echo "       -f deploy/contracts/$SLUG/compose.yml up -d --build"
echo
echo ">> Database for this tenant: $DB (isolated in the shared Postgres)."
