import { BadRequestException, NotFoundException } from '@nestjs/common';
import { EdiService } from './edi.service';
import { EdiDirection, EdiTransactionStatus } from './entities/edi-transaction.entity';
import { buildEdi850 } from './parsers/edi-x12.parser';

/**
 * EDI: inbound processing detects the transaction set from the ST segment,
 * parses a real X12 850, records failures on the transaction, and outbound
 * 850 generation round-trips through the builder.
 */
describe('EdiService', () => {
  let service: EdiService;
  let partnerRepo: any, txnRepo: any;

  const mockRepo = () => ({
    create: jest.fn((x: any) => ({ id: 'gen-1', ...x })),
    save: jest.fn((x: any) => Promise.resolve(x)),
    find: jest.fn().mockResolvedValue([]),
    findOne: jest.fn().mockResolvedValue(null),
    remove: jest.fn().mockResolvedValue(undefined),
    createQueryBuilder: jest.fn(),
  });

  const partner = {
    id: 'tp1', tenantId: 't1', partnerId: 'ACME', idQualifier: '01',
    senderId: 'US', senderQualifier: '01',
  };

  beforeEach(() => {
    partnerRepo = mockRepo(); txnRepo = mockRepo();
    partnerRepo.findOne.mockResolvedValue(partner);
    service = new EdiService(partnerRepo, txnRepo);
  });

  it('generateOutbound850 builds X12 content and records a SENT transaction', async () => {
    const { txn, rawContent } = await service.generateOutbound850('t1', 'tp1', {
      purchaseOrderNumber: 'PO-1001',
      vendorName: 'Acme Supplies',
      lineItems: [{ lineNumber: 1, quantity: 5, unit: 'EA', unitPrice: 9.99, productCode: 'SKU-1' }],
    });
    expect(rawContent).toContain('ST*850*');
    expect(rawContent).toContain('PO-1001');
    expect(txn.direction).toBe(EdiDirection.OUTBOUND);
    expect(txn.status).toBe(EdiTransactionStatus.SENT);
    expect(txn.referenceNumber).toBe('PO-1001');
  });

  it('processInbound parses an 850 generated by our own builder (round-trip)', async () => {
    const rawContent = buildEdi850({
      senderId: 'ACME', senderQualifier: '01', receiverId: 'US', receiverQualifier: '01',
      controlNumber: '000000042', purchaseOrderNumber: 'PO-2002',
      lineItems: [{ lineNumber: 1, quantity: 3, unit: 'EA', unitPrice: 20, productCode: 'SKU-9' }],
    });
    const txn = await service.processInbound('t1', 'tp1', rawContent);
    expect(txn.transactionSet).toBe('850');
    expect(txn.status).toBe(EdiTransactionStatus.PROCESSED);
    expect(txn.parsedPayload).toBeDefined();
  });

  it('processInbound rejects content without an ST segment', async () => {
    await expect(service.processInbound('t1', 'tp1', 'garbage-content')).rejects.toThrow('Cannot determine');
  });

  it('an unsupported transaction set fails the stored transaction', async () => {
    const txn: any = { id: 'txn1' };
    txnRepo.create.mockReturnValue(txn);
    await expect(service.processInbound('t1', 'tp1', 'ST*999*0001~')).rejects.toThrow('Unsupported transaction set');
    expect(txn.status).toBe(EdiTransactionStatus.FAILED);
    expect(txn.errorMessage).toContain('999');
  });

  it('partner lookups are tenant-scoped 404s', async () => {
    partnerRepo.findOne.mockResolvedValue(null);
    await expect(service.getPartner('t2', 'ghost')).rejects.toThrow(NotFoundException);
  });
});
